(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
  } else {
    root.lotteryTrades = factory();
  }
})(typeof globalThis !== "undefined" ? globalThis : this, () => {
  function normalizeName(value) {
    return String(value || "").trim();
  }

  function toSlot(value) {
    const parsed = Number(value);
    return Number.isInteger(parsed) && parsed > 0 ? parsed : null;
  }

  function getOriginalSlot(result) {
    const explicit = toSlot(result?.originalSlot);
    if (explicit !== null) return explicit;
    const standingIndex = Number(result?.standingIndex);
    return Number.isInteger(standingIndex) && standingIndex >= 0 ? standingIndex + 1 : null;
  }

  function formatTradeSummary(trade) {
    return `${trade.fromTeam} sends Pick #${trade.sendPick} to ${trade.toTeam} for Pick #${trade.receivePick}`;
  }

  /**
   * Computes the pick swaps needed to turn the pre-lottery draft order
   * (slot N belongs to the team that finished Nth-worst, held by that pick's
   * current owner) into the post-lottery order.
   *
   * Each result needs: pick (post-lottery slot), team (original team),
   * owner (current owner of that team's pick) and originalSlot or standingIndex
   * (pre-lottery slot, 1-based / 0-based respectively).
   *
   * Swaps are generated by walking the slot permutation and closing its cycles,
   * so a cycle of length k needs k - 1 swaps. Slots that do not move, and swaps
   * between two picks held by the same owner, are skipped.
   */
  function computeRequiredTrades(results) {
    if (!Array.isArray(results) || !results.length) return [];

    const holder = new Map();
    const target = new Map();
    const slotTeam = new Map();

    for (const result of results) {
      const pick = toSlot(result?.pick);
      const originalSlot = getOriginalSlot(result);
      const team = normalizeName(result?.team || result?.name);
      const owner = normalizeName(result?.owner) || team;
      if (pick === null || originalSlot === null || !owner) return [];
      if (target.has(pick) || holder.has(originalSlot)) return [];

      holder.set(originalSlot, owner);
      slotTeam.set(originalSlot, team);
      target.set(pick, owner);
    }

    const slots = [...target.keys()].sort((a, b) => a - b);
    const sameSlots = slots.length === holder.size && slots.every((slot) => holder.has(slot));
    if (!sameSlots) return [];

    const trades = [];

    slots.forEach((slot, index) => {
      const wanted = target.get(slot);
      const current = holder.get(slot);
      if (current === wanted) return;

      let swapSlot = null;
      let fallbackSlot = null;
      for (let i = index + 1; i < slots.length; i += 1) {
        const candidate = slots[i];
        const candidateHolder = holder.get(candidate);
        if (candidateHolder !== wanted || candidateHolder === target.get(candidate)) continue;
        if (target.get(candidate) === current) {
          swapSlot = candidate;
          break;
        }
        if (fallbackSlot === null) fallbackSlot = candidate;
      }
      if (swapSlot === null) swapSlot = fallbackSlot;
      if (swapSlot === null) return;

      const trade = {
        fromTeam: wanted,
        toTeam: current,
        sendPick: swapSlot,
        sendPickVia: slotTeam.get(swapSlot) || "",
        receivePick: slot,
        receivePickVia: slotTeam.get(slot) || "",
      };
      trade.summary = formatTradeSummary(trade);
      trades.push(trade);

      holder.set(slot, wanted);
      holder.set(swapSlot, current);
    });

    return trades;
  }

  return {
    computeRequiredTrades,
    formatTradeSummary,
  };
});
